name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop existing container (if running)
        shell: pwsh
        run: |
          if (docker ps -q -f name=my-app-container) {
            docker stop my-app-container
            docker rm my-app-container
          }

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run the container with environment variables
        run: |
          docker run -d -p 3000:3000 --name my-app-container \
            -e VITE_APP_DEV_PORT=${{ secrets.VITE_APP_DEV_PORT }} \
            -e VITE_APP_VERSION=${{ secrets.VITE_APP_VERSION }} \
            -e VITE_APP_TITLE="${{ secrets.VITE_APP_TITLE }}" \
            my-app:latest