name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Debug - Check if secrets exist
        shell: powershell
        run: |
          if ("${{ secrets.VITE_APP_DEV_PORT }}" -eq '') { Write-Error "VITE_APP_DEV_PORT is empty" }
          if ("${{ secrets.VITE_APP_VERSION }}" -eq '') { Write-Error "VITE_APP_VERSION is empty" }
          if ("${{ secrets.VITE_APP_TITLE }}" -eq '') { Write-Error "VITE_APP_TITLE is empty" }

      - name: Stop existing container (if running)
        shell: powershell
        run: |
          if (docker ps -q -f name=my-app-container) {
            docker stop my-app-container
            docker rm my-app-container
          }

      - name: Build Docker image
        run: |
            docker build -t my-app:latest `
              --build-arg VITE_APP_DEV_PORT="${{ secrets.VITE_APP_DEV_PORT }}" `
              --build-arg VITE_APP_VERSION="${{ secrets.VITE_APP_VERSION }}" `
              --build-arg VITE_APP_TITLE="${{ secrets.VITE_APP_TITLE }}" .

      - name: Run the container with environment variables
        shell: powershell
        run: |
              docker run -d -p 3000:3000 --name my-app-container -e "VITE_APP_DEV_PORT=${{ secrets.VITE_APP_DEV_PORT }}" -e "VITE_APP_VERSION=${{ secrets.VITE_APP_VERSION }}" -e "VITE_APP_TITLE=${{ secrets.VITE_APP_TITLE }}" my-app:latest
